name: api-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ci_db
      NODE_ENV: test
      JWT_SECRET: test-secret
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Sync DB schema (db push)
        run: npx prisma db push --accept-data-loss
      - name: Run tests
        run: npm test --silent
      - name: Build
        run: npm run build
